# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: oswaldo.vanegasg@gmail.com
author_name: Oswaldo Vanegas
has_binder: true
has_settings: false
kind: frontend
labextension_name: myextension
project_short_description: A JupyterLab extension.
python_name: myextension
repository: ''
test: true

